### ISSUE TITLE
希望能够支持第三方的 API Key 连接

### ISSUE THREAD

**Issue by Bian-Sh** [AkiKurisu/UnityChanDesktop#1]
如题，很多原因，会用到第三方提供的 API key 的情况，比如下面这个公益性 api key
https://github.com/chatanywhere/GPT_API_free
所以，希望能够支持修改 gpt url

**Comment by AkiKurisu** [comment]
感谢建议，如果api style和OpenAI的openapi一致的话，仅需要修改URL即可，我会增加一个额外的transport
